# Generated by Django 5.0.6 on 2024-07-03 12:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_chapter_task_chapter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='user_can_read',
            field=models.ManyToManyField(blank=True, related_name='tasks_can_read', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='visibility',
            field=models.CharField(choices=[('only_me', 'Только я'), ('everyone', 'Все'), ('selected', 'Выбранные пользователи')], default='only_me', max_length=20),
        ),
    ]
